### ISSUE TITLE
[DEV] Save folder detection in [unstable] can cause crash

### ISSUE THREAD

**Issue by Ironlion45** [wizzomafizzo/starcheat#113]
When looking for the Starbound directory, the editor is still looking for save game/universe data from furious koala, instead of the subfolder that unstable uses to store saved game information.   If there is no player or universe directory in /Starbound, the program will crash on launch.   However, if data is present in /starbound/player, the program will function properly, including reading/writing to /starbound/storage_unstable/player .  

The obvious workaround for this problem is to copy the /player and /universe directories from /storage_unstable into /Starbound.

**Comment by wizzomafizzo** [comment]
this isn't relevant any more after the latest changes
