### ISSUE TITLE
py-starbound crash on nightly

### ISSUE THREAD

**Issue by wizzomafizzo** [wizzomafizzo/starcheat#117]
Latest version of nightly, py-starbound is throwing errors that the assets file format is wrong, haven't seen any updates on the py-starbound project yet about it (will probably submit a bug later)

Most likely this is just a case of devs upping the version number rather than anything major

**Comment by wizzomafizzo** [comment]
Temporary fix is to change the assert on line 89 in sbbf02.py in py-starbound from SBBF02 to SBBF03. Everything is working fine again so I guess it was purely a version bump after all.

I've let blixt know and will have to see how he wants to handle it. Once it's patched we'll point to the new revision,

**Comment by chrmoritz** [comment]
Does this mean that we have to limit support to either unstable or nightly?

**Comment by wizzomafizzo** [comment]
I think we're fine then :)

I don't know how long blixt will take to make the update though. If it isn't before stable is released, is there a way we can inject the patch in the automated builds? Or would it be easier to temporarily fork the project (and using the hacky patch)?

**Comment by chrmoritz** [comment]
Applying a patch would be very easy. The more difficult part would be to document it well enough so that everyone cloning this repo is applying the patch to before opening a issue here (which they do not need to do if we fork it temporarily).

**Comment by wizzomafizzo** [comment]
I am leaning towards the temporary fork in that case. Let's just see how it pans out anyway, it's irrelevant until the new stable comes out and py-starbound could still be updated before then

Now that I got those changes in last night I'm pretty comfortable getting a release out as soon as starbound updates. Thanks for migrating everything to the github wiki btw, looks great!

**Comment by wizzomafizzo** [comment]
@chrmoritz ok looks like stable is out sooner than i expected

i made the fork here with the change: https://github.com/wizzomafizzo/py-starbound

is there anything special we need to do besides change the submodule?

**Comment by wizzomafizzo** [comment]
ok i just wasted an hour of my life trying to make that work but it won't stop using the old commit. can you please work your magic when you're around :(

**Comment by wizzomafizzo** [comment]
btw @chrmoritz is there a way we can make the appveyour build status icon work again? the broken image is bugging the hell outta me

**Comment by kurisubrooks** [comment]
@wizzomafizzo AppVeyor won't load at all for me, i'd say AppVeyor itself is broken, nothing you can do on your end.

**Comment by wizzomafizzo** [comment]
i hope there is a way to make it work again i hate making those dumb binaries :(

**Comment by chrmoritz** [comment]
I don't know why there was no build triggered, but I've triggered now a build on appveyor manually (maybe because there was no appveyor.yml on master at the time the tag was pushed).
@wizzomafizzo: BTW: You have to sign up there with your github account, I you want access to the builds too, because appveyor isn't as well integrated into github as travis.
