### ISSUE TITLE
Starcheat Dev won't compile in latest version

### ISSUE THREAD

**Issue by kurisubrooks** [wizzomafizzo/starcheat#118]
Kurisu$ brew reinstall https://raw.github.com/wizzomafizzo/starcheat/dev/mac/starcheat.rb --HEAD
######################################################################## 100.0%
==> Reinstalling starcheat with --without-app
==> Cloning https://github.com/wizzomafizzo/starcheat.git
Updating /Library/Caches/Homebrew/starcheat--git
fatal: reference is not a tree: 262fb9f86dbe6130012e3a4a1db5458b9783f7ec
Unable to checkout '262fb9f86dbe6130012e3a4a1db5458b9783f7ec' in submodule path 'starcheat/starbound'
Error: Failed to download resource "starcheat"
Failure while executing: git submodule -q update --init --recursive

**Comment by kurisubrooks** [comment]
I did a $brew uninstall starcheat then redid $brew install starcheat, now it compiles properly. strange.

**Comment by wizzomafizzo** [comment]
by the looks of it homebrew is keeping a cached copy of the git repo which could explain it. i can't say if it's a problem with how we switched py-starbound repos or just with git itself but i had to reclone the whole repo to make it update properly

**Comment by kurisubrooks** [comment]
Yeah, I deleted the cache and uninstalled and reinstalled, worked fine!

**Comment by chrmoritz** [comment]
Yeah, you have to run `git submodule sync` if you want to use a existing copy of the repo with the new submodule.

**Comment by kurisubrooks** [comment]
'tis stupid.

**Comment by chrmoritz** [comment]
It's more or less a bug in homebrew not supporting submodule changes.

**Comment by chrmoritz** [comment]
My PR fixing this issue was merged by homebrew so this should be a problem when we switch the submodule back after it is compatible with stable again.
