### ISSUE TITLE
appveyor bugged for repo colaborators

### ISSUE THREAD

**Issue by chrmoritz** [wizzomafizzo/starcheat#122]
@wizzomafizzo: Looks like appveyor is bugged if its setuped by a repo colaborator and not the owner of the repo. Could you please:
* [sign in](https://ci.appveyor.com/) to https://ci.appveyor.com/ with GitHub OAuth
* add the starcheat github repo to your projects
* check the general setting `Skip branches without appveyor.yml` and leave all other settings unchanged
* update the appveyor badge and [revert this change](https://github.com/wizzomafizzo/starcheat/commit/a389b15fa1c2b2cdb3f7c92c81078c2950d6d0f7#diff-180360612c6b8c4ed830919bbb4dd459L5)
* and maybe add me as a collaborator in appveyor (but you will need my real email for doing so, so write me on steam because I don't wont to post it here)

**Comment by chrmoritz** [comment]
for now I've built the windows binaries in my fork and downloaded them form there and uploaded them here

**Comment by wizzomafizzo** [comment]
cool as, i've done up to step 3 now. i'll give ya a shout on steam later

**Comment by chrmoritz** [comment]
btw: you get the badge under `settings` -> `badges` -> `Sample markdown code` (not the master branch badge because we are building from tags)

**Comment by chrmoritz** [comment]
I'm using now a shield.io badge for appveyor, which looks much better then the normal appveyor badge, because it's in the same style of every other open source badge available.
For comparison: [odd appveyor badge](https://github.com/chrmoritz/Troxel/blob/d029c18fe81b2778f6f9fbeab07d7713c72b024f/README.md) and [nice shield.io badge](https://github.com/chrmoritz/Troxel/blob/master/README.md)

**Comment by chrmoritz** [comment]
now I'm getting very confused...
Why is AppVeyor building a very old commit instead of the tag? This makes absolutely no sense assuming you didn't messed the settings up.

**Comment by wizzomafizzo** [comment]
it's not configured at all, the only thing i did was check that setting you said in the 3rd step. send me your email on steam now i'll give you access when i'm home

**Comment by chrmoritz** [comment]
done.
btw: Did you have abort the 64 bit build? because it's `Build has been cancelled by user.` and I don't have the rights yet to do so.

**Comment by wizzomafizzo** [comment]
I deleted it last night, I will set it up again tonight and give you access

**Comment by chrmoritz** [comment]
I really hope that this will resolve the strange issues finally.

**Comment by wizzomafizzo** [comment]
ok i recreated it and ticked ignore branches without appveyor file, didn't touch anything else

you should still be collaborator

**Comment by chrmoritz** [comment]
looks like it is somehow working now, let's see if this is still the case when we push the next tag
