### ISSUE TITLE
Old .file's not working

### ISSUE THREAD

**Issue by Flipdecoin** [wizzomafizzo/starcheat#123]
The old .file's that I would export items as to save them are not being accepted into the new version of starcheat. Theyc an be fixed to fit, although it requires changing most of the code in a notepad for each item. Is there any way you could make it so that the old files are accepted and maybe translated to the new .json format needed for the game?

**Comment by chrmoritz** [comment]
Sorry, but there are atm no intention to make starcheat backwards compatible with previous Starbound versions.

**Comment by Flipdecoin** [comment]
Alright. I have figured out how to transfer the attributes and make the old files compatible forward though, and its not that many lines, so its fine.

**Comment by archfiendrubicante** [comment]
Changing the "data" on the third or fourth line of code to "parameters" gives the file some degree of transposition, but the data isn't the same coding in the game currently, so the resulting item isn't going to look the same 100% of the time.

**Comment by wizzomafizzo** [comment]
does that mean that starbound accepts and still uses item that have the data field on them? i remember changing it to parameters because that's what nightly started using, but if starbound still also accepts the old style i can add an exception to allow it

**Comment by Flipdecoin** [comment]
Nightly and the newest update switched just enough variable naems around to screw up the old file from enraged koala and back. "data" went to "parameters", "kind" went to "stat", and some of the statuseffects changed. "inspectionkind" changed to "tooltipKind", but on some. If your trying to import a gun, then only changing "data" to "parameters" is fine, but swords and armor are slightly more challenging. I have pulled all of whta I found here: http://community.playstarboundrp.com/threads/starcheat-file-json-damage.8167/
It's not complete, but i should work 90% of hte time when converting old files.

**Comment by wizzomafizzo** [comment]
Unless you can come up with a simple fix to this issue I think I need to close it off

It will be extremely complicated to make all these conversations and all the work will be for nothing as soon as the initial lot of items are converted. I'd prefer to leave it up to the user to convert by hand or someone else to make a conversion tool

I forget how starcheat current reports errors when importing items. If it still fails silently please let me know, I will add something to give better error feedback through this ticket

**Comment by wizzomafizzo** [comment]
K gonna close this now. If you have any tricks to do the conversion please let me know and I can reopen

**Comment by wizzomafizzo** [comment]
oh btw, if you've got anything you'd like to add to the wiki about this please let me know too
