### ISSUE TITLE
Character not showing up after editing them

### ISSUE THREAD

**Issue by archfiendrubicante** [wizzomafizzo/starcheat#124]
Changing a stance from starcheat removes the character from the selection library.

**Comment by chrmoritz** [comment]
I couldn't reproduce this, so at least not all personalities from all races are affected.
Can you please add some detail to which personality of which race you have changed your character and if that was the only change you did. Providing [logs](https://github.com/wizzomafizzo/starcheat/wiki/help#how-to-get-logs) and the corrupted player file would be helpful too.

**Comment by archfiendrubicante** [comment]
Sure. Can do. I'll copy my starbound directory for you in dropbox. At the time it was a Human(F), and I changed from Personality 5 to Personality 4.

Link to dropbox below: 
https://www.dropbox.com/s/8u21xsqgwfef4j9/player.rar?dl=0

**Comment by archfiendrubicante** [comment]
Here's the Starcheat logs as well:
https://www.dropbox.com/s/zbllae12j9rjlah/starcheat%20logs.rar?dl=0

**Comment by archfiendrubicante** [comment]
Another instance of it happening on an Avian Male after changing the character description complete with logs and character files: 
https://www.dropbox.com/sh/0k1web9vsd8qqr6/AABV5GfTwPUyoW0wtXH588N6a?dl=0

**Comment by archfiendrubicante** [comment]
My Skype is the same as my username if you need to corroborate with me.

**Comment by archfiendrubicante** [comment]
https://www.dropbox.com/s/5lpn784jz854tat/starcheat%20logs.zip?dl=0

Human, Female:
I gave Ether all blueprints, then got diamond armor for Ether, as well as Adventurer's helmet, then I went to look at the color codes for the diamond chestplate, copy/pasted those into the helmet's as necessary, tried playing, and character vanished.

**Comment by archfiendrubicante** [comment]
Thusfar I've tried duplicating the issues using completely new characters and modifying variables in Starcheat and nothing seems to be triggering the characters to not appear on a NEW character.

**Comment by archfiendrubicante** [comment]
Hmmm.. An interesting thing of note.
Since the character no longer shows up after this bug occurs, It allows you to create a character with the same name in game, after exiting starbound and opening starcheat, and deleting the corrupted character, the other character with the same name instantly pops up.

**Comment by Patchumz** [comment]
I changed my gender and hairstyle on a Upbeat Giraffe character (brand new) and it disappeared from the character screen. I've only beaten the first two bosses and fixed my FTL drive so far.

**Comment by wizzomafizzo** [comment]
@Patchumz starbound error
[23:17:12.410] Error: Failed to valid player with uuid 0bee4ed39be8089db79fa49edd22c998 : (VariantException) No such key in Variant::get("module")

@archfiendrubicante starbound error
[23:20:36.225] Error: Could not instantiate item '[generatedsword, 1, {"level":1,"fireAfterWindup":true,"drawables":[{"image":"/particles/ash/3.png?setcolor=1B1917","position":[0,33]},{"image":"/particles/ash/3.png?setcolor=36312D","position":[0,34]},{"image":"/particles/ash/3.png?setcolor=6F777B","position":[5,45]},{"image":"/particles/ash/3.png?
**SNIP**
{"speed":0.1,"power":5,"level":1}},"shortdescription":"Canine Hoverbike","weaponType":"Hoverbike","itemName":"generatedsword","levelScale":2}]'. (VariantException) No such key in Variant::get("stat")
[23:20:36.235] Error: Failed to valid player with uuid 332cece52540f936703332b591500c8a : (VariantException) No such key in Variant::get("module")

**Comment by wizzomafizzo** [comment]
will find out what that module key is it's looking for in both characters. not sure what that hoverbike thing is about with the billion particle images?

**Comment by MavJones** [comment]
I was having the same issue, and yes I tried editing appearance as a whole, which maybe it's the appearance section that's causing the bug I've really no idea. I had starcheat work before but the conditions triggering the bug are unknown to me.

**Comment by MavJones** [comment]
Alright, so as far as I can tell it's in the appearance section, if I leave the appearance be, everything else seems to work.

**Comment by Sakarias-Longhorn** [comment]
Oh no, this happened to me, I can't load my character anymore !

** (VariantException) No such key in Variant::get("module") **

**Comment by MavJones** [comment]
I was doing some trial and error. Appearance and Tech can bug the game, so if you choose to learn all tech do not equip the tech until you're in the game otherwise you may bug the character.

**Comment by Sakarias-Longhorn** [comment]
I didn't even edited the tech or appearance... and it corrupted my save.

**Comment by Ristovski** [comment]
Can confirm, editing characters (happened while editing *Tech*) **corrupts** the character file, "*No such key in Variant::get("module")*". This happened to me in the Nightlies aswell.

**Comment by MavJones** [comment]
I think it's mostly tech, they took some techs out, like the cameraman boost which corrupted the file in my tests.

**Comment by wizzomafizzo** [comment]
can any techs be equipped through starcheat or is it 100% failing? can confirm with is one of the causes but it will still take some investigation to see if it can be fixed from starcheat's end. at least clearing equipped techs makes it work again

i haven't been able to reproduce the same issue with the appearance dialog yet. stance and hair/face/wtc changes are working fine

**Comment by TheDreamweaver** [comment]
SO appears that simply unequipping the tech in starcheat will make the character loadable again.

**Comment by Patchumz** [comment]
I can confirm what @TheDreamweaver said. Even though I didn’t touch the techs or anything, unequipping them in starcheat enabled me to see my character on the character select screen again.

**Comment by chrmoritz** [comment]
Any chance we can get a player file of a working character with at least 1 tech directly earned ingame immediately before editing with starcheat and a version of the same now broken player file after doing a very simple change (e.g. changing one appearance slot only) after exporting it with starcheat?

**Comment by chrmoritz** [comment]
I've uploaded a simple test case of a working player file and a broken player file with as minimal changeset as possible between both files: https://github.com/chrmoritz/starcheat/releases/download/0.6.0/startest.tar.gz

**Comment by MavJones** [comment]
Yeah, the problem is equipping, not unlocking, I would have said that last night, but I was at work.

**Comment by chrmoritz** [comment]
Could you please try [version 0.19](https://github.com/wizzomafizzo/starcheat/releases/tag/0.19) and report back if this has fixed your issue.

**Comment by Sonador** [comment]
Techs must till be unequipped prior to load.

**Comment by Lyynus** [comment]
I have tried this, but my character is still corrupt and not having the tech equipped hasn't seemed to fix the problem.

**Comment by Lyynus** [comment]
I'd actually like to apply a little update to what I had said before (In hopes people will respond). So just by testing and see if it was something that had been mentioned before to see if what everyone else had suggested may fix it (Like taking off all tech) but thats not the case. Apparently every character that I overlook in the starcheat application ends up being not even in-game when it gives you the character selection screen. It doesn't matter whether I add or modify anything or not it will still hide the character without me doing anything. Any help?

**Comment by wizzomafizzo** [comment]
I'm sorry you're having these issues, I saw the comment but I don't have any instant fixes up my sleeve

The best thing you can do is upload a copy of at least one of the affected characters somewhere (metadata included) and a copy of your starbound.log file (in the Starbound giraffe_storage I think) immediately after you enter the character selection screen

If starcheat itself is giving errors, upload a log of that, but don't bother if starcheat is acting normal

**Comment by Lyynus** [comment]
Starcheat is acting normal the only abnormality I'm finding is that after I open a character using starcheat then go to the Starbound game that character is not in the character selection anymore, but still accessible using starcheat.  Here are the files with the first character I had this happen too and the logs. https://www.dropbox.com/sh/p9q2mug32lyu00p/AADFwzXfKHqdZ-Jw21c2cWMva?dl=0

**Comment by wizzomafizzo** [comment]
relevant log entries:
```
[20:47:19.300] Error: Could not load /items/armors/backitems/slimcape/slimcapebackicon.png asset, using placeholder default.
(AssetException) No such asset '/items/armors/backitems/slimcape/slimcapebackicon.png'
[20:47:22.853] Error: Could not instantiate item '[stupidlybrokenbackitem, 1, {}]'. (VariantException) No such key in Variant::get("stat")
[20:47:22.855] Error: Could not instantiate item '[stupidlybrokenbackitem, 1, {}]'. (VariantException) No such key in Variant::get("stat")
[20:47:28.841] Error: Could not instantiate item '[rabbitshot, 1, {}]'. (ProjectileDatabaseException) Unknown projectile with typeName kurousagi.
[20:47:28.843] Error: Could not instantiate item '[rabbitshot, 1, {}]'. (ProjectileDatabaseException) Unknown projectile with typeName kurousagi.
[20:47:30.439] Info: Done loading Star::Root.
[20:47:30.441] Info: Renderer destroyed
[20:47:33.039] Error: Error loading player file, ignoring! .\../giraffe_storage\player\9778db5c589e4761c959751b3490e5d8.player : (DataStreamException) Error reading VLQ encoded intenger!
[20:47:33.383] Error: Error loading player file, ignoring! .\../giraffe_storage\player\e3d6157be7687d8d91f0808765dd0f3f.player : (DataStreamException) Error reading VLQ encoded intenger!
[20:47:33.383] Error: Error loading player file, ignoring! .\../giraffe_storage\player\nf84hf0dmd7flp894hg03n58fjf93na93h.player : (UuidException) Size mismatch in reading Uuid from ByteArray: 17 vs 16
```

these are all new errors
- first 5 lines, i assume this is being caused by a mod not defining items correctly. don't think it's fatal or the cause of the issue with player files
- next 2 lines, seems that starcheat is not writing player files correctly for you which is the first i've seen in at least a year. will need to investigate more when i'm home, very strange since nobody else has reported similar issues
- last line, the filename/uuid look completely wrong, i don't think it's meant to have characters outside the hex range

@Lyynus i can't say for sure what's going one yet. for that last one, did you change the filename or anything like that? or is that just how it's ended up by itself? it is a long shot as well, but if you haven't already done so, i'd suggest deleting and reinstalling starbound from scratch, and trying it all again with no mods installed

@chrmoritz not sure if you have any ideas or not but you probably wanna see this anyway, it's pretty unusual

**Comment by Lyynus** [comment]
Wow... thats unique. Other characters not used in starcheat work just fine and to my knowledge all my player files have been stored in the same place and had worked before just fine until yesterday when I had overlooked that character and (I think) only changed amounts in pixels I had then had it save before getting on Starbound, then I wasted a day testing theories and making new characters but it seems no matterr what I did as long as I at least opened a character in starcheat they did not load in the Starbound game. (I know Im probably repeating myself at this point, but I find it difficult to understand why the files would save else where and as to of what's corrupting them) I'm also not the only one a friend of mine is also experiencing the same problem and we wasted a day on collaborating to try and fix the issue, but that didn't seem to work out. Thanks for all your help.

**Comment by wizzomafizzo** [comment]
@Lyynus delete these 2 items

![2015-02-10 23_56_37-starcheat - lyynus_](https://cloud.githubusercontent.com/assets/442478/6131080/7a50bf90-b184-11e4-8f2d-be64c7ab080c.png)

these are the items

```
{
    "count": 999,
    "name": "handgrenade",
    "parameters": {
        "ammoUsage": 0,
        "cooldown": 0.0,
        "description": "Nuclear!",
        "edgeTrigger": true,
        "image": "grenadeicon.png",
        "inventoryIcon": "grenadeicon.png",
        "itemName": "handgrenade",
        "projectileConfig": {
            "power": 100000000000000000000000000,
            "speed": 3000000000000000000000
        },
        "projectileType": "nuclear",
        "rarity": "Legendary",
        "shortdescription": "Nuclear Grenade",
        "windupTime": 0.0
    }
}
```

```
{
    "count": 999,
    "name": "electrogrenade",
    "parameters": {
        "ammoUsage": 0,
        "cooldown": 0.0,
        "description": "Electric grenade. Made to devastate.",
        "edgeTrigger": true,
        "image": "electrogrenadeicon.png",
        "inventoryIcon": "electrogrenadeicon.png",
        "itemName": "electrogrenade",
        "projectileConfig": {
            "level": 150,
            "power": 55000000000000000000000000000,
            "speed": 450000000000000000000
        },
        "projectileType": "electrogrenade",
        "rarity": "Legendary",
        "shortdescription": "Electric Gren",
        "windupTime": 0.0
    }
}
```
specifically the projectileconfig numbers in both. they are too big for starbound to handle. i couldn't figure out the exact number that trips it but i can reliably cause the corruption by changing the numbers from low to very high. i can say it is somewhere between the highest 64 and 128 bit value

i don't think this can really be something starcheat checks for you, it's gonna be something you just have to keep in mind while editing and playing with the mods. maybe it can be added someone on the wiki

**Comment by OrdainedCptn** [comment]
Hey, I'm having just about the same problem. My character file data won't load right and I had taken what happened to Lyynus into account and tried checking everything I had but it didn't seem that anything was wrong. Mind taking a look for me and helping me out? It'd be much appreciated! Thank you! https://www.dropbox.com/sh/nkb2fdruwajbsfq/AACKCOJLYhFAkPw5AB4kh3iLa?dl=0

**Comment by Lyynus** [comment]
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 74, in <module>
  File "build\starcheat.py", line 71, in main
  File "build\gui\mainwindow.py", line 134, in __init__
  File "build\gui\mainwindow.py", line 417, in open_file
  File "build\gui\utils.py", line 330, in __init__
  File "build\gui\utils.py", line 364, in populate
  File "build\assets.py", line 1094, in render_player
TypeError: 'NoneType' object is not subscriptable

Thanks for your help again. I'll just upload an updated version with both my characters and their player files with updated logs.

https://www.dropbox.com/sh/p9ybdeuchj4p7i9/AACwvupMTobrbCQxbO_riPo7a?dl=0

**Comment by wizzomafizzo** [comment]
@OrdainedCptn try this: https://mega.co.nz/#!skh2RJIR!ABmTSlb4OOJ8r5Skg10NQ_BN_fnU7Gpw3-j0TEfYbYI

your player had extra stats starting with mmx_ that starbound couldn't handle. most likely this was caused by a mod

**Comment by wizzomafizzo** [comment]
@archfiendrubicante can you confirm if everything is working now with the latest release?

i think that's everything covered in this ticket that isn't also in another open ticket

**Comment by archfiendrubicante** [comment]
I've tested the latest release and from what I can tell I haven't seen any
issues with minor edits removing the character from selection, most issues
now that cause data corruption are limited to items that don't fit the
parameters of the game.

**Comment by wizzomafizzo** [comment]
i think that's the best we're ever gonna do. thanks for your initial report! let me know if this needs to be reopened
