### ISSUE TITLE
Crash In Tech selector

### ISSUE THREAD

**Issue by Josecroudo** [wizzomafizzo/starcheat#130]
When i open the tech selector to put more techs in my character the starcheat crashes and corrupt my player file, and i cant use the player anymore in starbound. Version 0.18.1

**Comment by wizzomafizzo** [comment]
hi, could you please upload a copy of the player file somewhere so i can see what happened? i may be able to recover it too if you want

**Comment by sirkey** [comment]
its not about recover character,its about we cant use tech in your starcheat

**Comment by chrmoritz** [comment]
Could you please try [version 0.19](https://github.com/wizzomafizzo/starcheat/releases/tag/0.19) and report back if this has fixed your issue.

**Comment by chrmoritz** [comment]
This should be fixed in 0.20. Closing this because of lack of detailed information an no response.
