### ISSUE TITLE
Human Mech

### ISSUE THREAD

**Issue by Broswirl** [wizzomafizzo/starcheat#132]
Traceback (most recent call last):
  File "build\gui\techs.py", line 64, in __init__
  File "build\assets.py", line 1330, in get_tech
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build\gui\mainwindow.py", line 387, in new_techs_dialog
  File "build\gui\techs.py", line 71, in __init__
KeyError: 'modulePath'

**Comment by MavJones** [comment]
This issues is being covered in #124 and #131.

I've done testing, do not equip techs using Starcheat wait until you're in-game, cause even if you unlock "all" the techs not all will show up for your given character. If you equip an incompatible tech it appears to corrupt the player file, forcing it to not show up in your character list.

**Comment by Broswirl** [comment]
Is there a Method to Manually remove the tech?

**Comment by MavJones** [comment]
Not that I know of. This is why when using starcheat it's highly advised to make backups. I did a bunch of tests to see what the problem was and tech was it as far as I could tell.

**Comment by sirkey** [comment]
so,basicly all we have to do-is doesnt use not race mech?

**Comment by sirkey** [comment]
do not use any cars,jeeps or mech.Its the issue of the problem.Hope someone will find this helpful

**Comment by chrmoritz** [comment]
Could you please try [version 0.19](https://github.com/wizzomafizzo/starcheat/releases/tag/0.19) and report back if this has fixed your issue.

**Comment by Broswirl** [comment]
Bug is fixed!
