### ISSUE TITLE
Mods won't load

### ISSUE THREAD

**Issue by Markelius** [wizzomafizzo/starcheat#136]
Mods do not appear to load in the new version. I suspect it's looking for mods in the root rather than in /giraffe_storage/, but I cannot confirm this.

Furthermore, selecting mod-added items in the inventory editor crashes Starcheat, since it can't read data for them.

**Comment by chrmoritz** [comment]
Should be fixed in dbf1682. Could you please try and verify this.

**Comment by chrmoritz** [comment]
Binaries for this are now up at https://github.com/chrmoritz/starcheat/releases/tag/0.18.2 for testing.

**Comment by Markelius** [comment]
Yep, that fixed it. Thanks!
