### ISSUE TITLE
Can't unequip a Tech that you should not able to equip (maybe?)

### ISSUE THREAD

**Issue by Pinkay** [wizzomafizzo/starcheat#139]
Hey there, had problems with my save file the last 2 hours.

It seams like i have equiped a tech that I am not suposed to have equiped..

This is a Screenshot of the situation ..
![ss 2015-02-03 at 11 26 15](https://cloud.githubusercontent.com/assets/10828497/6018573/0b24705e-ab98-11e4-9246-6e7a790daeb9.png)

Error:

Traceback (most recent call last):
  File "build\gui\techs.py", line 52, in <lambda>
  File "build\gui\techs.py", line 164, in set_select
  File "build\gui\techs.py", line 130, in update_selection
  File "build\assets.py", line 1330, in get_tech
TypeError: 'NoneType' object is not subscriptable

**Comment by wizzomafizzo** [comment]
i think this latest patch should allow you to open up and recover the player now

i'm still investigating but i think the underlying cause for the ghost tech is because i use a very lazy method to match up tech items to their tech module scripts, it was too slow to load otherwise. if that's actually what's happening, the fix will be to add module names to the index database

**Comment by Pinkay** [comment]
It still gives me the error when I try to click on the "gravitybubbletech" tech. Also the savegame is corrupted after I just switch in some other tech's.

Error :

Traceback (most recent call last):
  File "build\gui\techs.py", line 52, in <lambda>
  File "build\gui\techs.py", line 164, in set_select
  File "build\gui\techs.py", line 130, in update_selection
  File "build\assets.py", line 1331, in get_tech
TypeError: 'NoneType' object is not subscriptable

Also, screenshot from the Situation 
![ss 2015-02-03 at 03 32 47](https://cloud.githubusercontent.com/assets/10828497/6022036/6462f506-abba-11e4-9e4d-a0535d20d0e8.png)
:

**Comment by chrmoritz** [comment]
It's fixed in the latest commit on the dev branch, but not in the version you are using.
