### ISSUE TITLE
MAGMIS mod currupts player file

### ISSUE THREAD

**Issue by newprex** [wizzomafizzo/starcheat#149]
http://pastebin.com/7Mkwdjda

As you can see, I tried 0.18.2, 0.19 64bit(yes pc is 64 bit)/32bit and got same crash, tried to clean up starcheat.ini and assets.db each times between those attempts.
Hope you can help me, and that my error can help you if anybody got it too.

**Comment by chrmoritz** [comment]
Looks like you have an outdated mod installed. Currently starcheat crashes if it tries to index a mod with an outdated format version while Starbound just ignore it. Try to remove all mods not updated for upbeat giraffe from your mods folder.

**Comment by Alhrguy** [comment]
I'm having a similar issue, only all of my mods are updated. I even uninstalled a mod I made myself specifically for this version. I tried re-installing them, and starcheat felt the need to crash again. I uninstall the mods after that, and it still crashes. I'm lost, here.

**Comment by newprex** [comment]
This problem comes when i tried to update from 1.8.1 to 1.9 if it can help, i tried looking mods 1 by 1, each one is updated and run perfectly ingame, but they have pak.modinfo instead of nameofmod.modinfo, probably not important but ill try to rename to nameofmod.

**Comment by wilbee10091** [comment]
Traceback(most recent call last):
 File "C:\Python34\lib\site-packages\cx_Freeze\initscripts
\Console.py", line 27, in <module>
 File "build\starcheat.py", line
74, in <module>
 File "build\starcheat.py", line 71, in main
 File "build\gui
\mainwindow.py", line 67, in _init_
 File "build\gui\utils.py", line 95,
in check_index_valid
 File "build\gui\utils.py", line 57,
in build_assets_db
 File "build\assets.py", line 228
in find_assets
 File "build\assets.py", line 234,
in scan_modpack
 File "build\starbound
\helpers.py", line 213, in open
 File "build\starbound
\helpers.py", line 220, in read_stream
 File "build\starbound
\btreedb4.py", line 119, in
initialize
 File "build\starbound
\sbbf02.py", line 89, in initialize
AssertionError: Invalid file format



Plz help me ive tried multiple version removed mods clean install everything plz tell me what is wrong here

**Comment by chrmoritz** [comment]
What version of Starbound are you using? Starcheat 0.18-0.19 is only compatible with the current stable version upbeat giraffe.

**Comment by wilbee10091** [comment]
18.0-19.0 tried with all of them same error and I have upbeat giraffe

**Comment by chrmoritz** [comment]
Looks like you have an outdated mod in the `giraffe_storage/mods` folder.

**Comment by wilbee10091** [comment]
thanks it was skyrail sits

**Comment by newprex** [comment]
In fact, 1.8.1 is working, so it's  a change between this version and others

**Comment by chrmoritz** [comment]
1.8.2+ has fixed mod support for upbeat giraffe. Just get rid of the not updated mod in `giraffe_storage` and it should work

**Comment by newprex** [comment]
I tried to rebuild assets without my mods and import them, works fine, but now when i try to edit something to my player, my player become not readable by starbound, checked the starbound logs, says the error is over my description, so i modified it with no results, here is my log:
http://pastebin.com/2Pp8gzCK

Hope it can help.

**Comment by wizzomafizzo** [comment]
@newprex i think you have an item in your inventory that is missing a description field. keep deleting items until you track down which one is causing the problem

**Comment by newprex** [comment]
So, i tried removing all my inventory items and armors and i works, so now im gonna try to corner the bad item.
Thanks for the help

**Comment by newprex** [comment]
Ok, cornered a MAGMIS modified weapon, which include special symbols into description, gonna try to see if others ppl got this on the starbound forum page of the mod and if the author would like to modify the description output for his mod.

**Comment by chrmoritz** [comment]
what special symbols are you talking about?

**Comment by chrmoritz** [comment]
Everyone having issues with mods in the old sbbf02 format should try out [version 0.19.1](https://github.com/wizzomafizzo/starcheat/releases/tag/0.19.1) which should fix your issues.

**Comment by newprex** [comment]
Well, i managed to get it working without removing or updating any mod, in fact, it was a symbol added by MAGMIS mod on a modified weapon's description who was working with vanilla starbound but it it would render character unreadable by starbound if them modified by stacheat.

To make it simple:
Vanila weapon+MAGMIS mod >Working, description shows a symbol added by MAGMIS mod,
This weapon + starcheat > Not working, logs says error in description of the weapon, surely added with the symbol of MAGMIS.
So the symbol of MAGMIS doesn't seems to be readable by starbound after player files got edited with starcheat.

**Comment by wizzomafizzo** [comment]
hey @newprex could you give the MAGMIS mod another shot with the latest release and let us know if it works. i have just tested it and it seems to be working fine

**Comment by newprex** [comment]
Still not working with lastest, here are all the infos :

starbound.log :
http://pastebin.com/VMSjT0gY

starcheat.log :
https://www.dropbox.com/s/3uj6mhi5fi81pkj/starcheat.log?dl=0

player file :
https://www.dropbox.com/s/yz0xn6ruv4xph7n/573d6c2245a6cbbdee59f1350a488439.player?dl=0

The only way to duplicate the bug is to modify a weapon with MAGMIS and then use starcheat on the same character.Removing the modded item restore player for starbound.

**Comment by wizzomafizzo** [comment]
"Ô AGMIS"

**Comment by chrmoritz** [comment]
hmm, `ord('Ô')` says that this is a valid ASCII character (212)

**Comment by wizzomafizzo** [comment]
i have gotten it saving a non-corrupt save changing the pack string function
```
def pack_vlq_str(var):
    if var == "":
        return b"\x00"
    string = pack_str(var)
    vlq = pack_vlq(len(string))
    return vlq + string
```
before it counted the number of characters, now it counts the number of bytes, which makes more sense

it can write the Ô and other utf8 strings just fine the first time, the look fine in starbound, but if you read it back into starcheat it gets converted back as a non-utf8 string. in starcheat it looks like Ã”Â and on subsequent write will look like that in starbound too

still figuring it out

**Comment by wizzomafizzo** [comment]
got it

**Comment by chrmoritz** [comment]
@newprex : This should be fixed now. Please report back and reopen this issue if your problems persist in [starcheat 0.20](https://github.com/wizzomafizzo/starcheat/releases/tag/0.20).

**Comment by newprex** [comment]
Issue is resolved, thanks for the good work @chrmoritz and @wizzomafizzo .

**Comment by wizzomafizzo** [comment]
no worries, glad to hear it's working! thanks for the report
