### ISSUE TITLE
Raw JSON "Image" tags

### ISSUE THREAD

**Issue by FoggyPaws** [wizzomafizzo/starcheat#152]
So, I added a ?replace string at the end of an image directory, in an image tag
where the raw json would be:

image

"/humanoid/blahblah.png?replace;blahblahblah"
just for example
I have everything right, but Starcheat seems to freak out after I add ?replace in raw, like it's expecting nothing but a file location, but instead it's got all this extra ?replace gobldygook.
As soon as I close the raw JSON box, an error pops up, I ignored it, closed the item properties box, another error, saved the file, and closed the program.

Everything works smooth in game, no problems, but when I open Starcheat again to make changes, I get this error.

Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 74, in <module>
  File "build\starcheat.py", line 71, in main
  File "build\gui\mainwindow.py", line 134, in __init__
  File "build\gui\mainwindow.py", line 426, in open_file
  File "build\gui\mainwindow.py", line 197, in update
  File "build\gui\mainwindow.py", line 554, in update_bag
  File "build\gui\common.py", line 89, in __init__
  File "build\gui\common.py", line 38, in inv_icon
  File "build\assets.py", line 446, in color_image
  File "build\assets.py", line 438, in do_replace
UnboundLocalError: local variable 'new_image' referenced before assignment

I'll recreate the first errors again, just thought I'd put this here

Starcheat is the ver 0.18.1
I'm using the current Stable Branch, Upbeat Giraffe, it's 2/7/15 (M/D/YY)

**Comment by wizzomafizzo** [comment]
i think i'll be looking into this one next since it seems pretty severe for the modding side of starcheat

thanks for your bug report btw it is very thorough, much appreciated

**Comment by wizzomafizzo** [comment]
can't make a patch until later but here is the offending line:
https://github.com/wizzomafizzo/starcheat/blob/dev/starcheat/assets.py#L447

i expect it happens for the others too. i think something is tripping up because of this silly mix i've done where i expected do_replace to both set an outside variable and return an image (which it doesn't)

should be easy enough to do some cleanup and make it work purely with params and return vals, even if that doesn't fix it it will make it easier to troubleshoot

**Comment by wizzomafizzo** [comment]
actually scratch that, it's a different function doing the return so not problem there. still will make a change to it though rather than relying on these poor man's closures working

**Comment by FoggyPaws** [comment]
Good to know that it's in the pipes for a fix.
As of now I can still make the items with ?replace and they function just fine, it's just going to be nice to open them back up and make changes if need be.

**Comment by wizzomafizzo** [comment]
would you be able to go through the steps for me again. i can't seem to reproduce this. i am
- generating a new item (sword) with a plain image key
- edit raw json on image key
- replace with "/humanoid/blahblah.png?replace;blahblahblah"
- OK
- try edit normal
- try edit raw json

but everything seems to be working fine, no errors

**Comment by FoggyPaws** [comment]
So I open Starcheat, and load up my character, everything is normal.
https://www.dropbox.com/s/kdvq9ecx7ctevau/Screenshot%202015-02-10%2019.26.17.png?dl=0

I open up an item that doesn't use "drawables" like the Alien Laser Gun
https://www.dropbox.com/s/oxx6miespgwtiwf/Screenshot%202015-02-10%2019.27.39.png?dl=0

I open up Raw JSON, and this is what I see by default
https://www.dropbox.com/s/tc6a8f9ay29002d/Screenshot%202015-02-10%2019.27.48.png?dl=0

I add my ?replace data "?replace;23063A=390607;643388=883335;75409A=9B4242;8C4EBE=BF5050;B686D1=D18787"
https://www.dropbox.com/s/26hibektbrmyyya/Screenshot%202015-02-10%2019.28.01.png?dl=0

I get this error immediatlly after closing Raw JSON editor
https://www.dropbox.com/s/wo45j83coxh2ite/Screenshot%202015-02-10%2019.28.11.png?dl=0

And I get this error after closing the item properties menu
https://www.dropbox.com/s/8w3bc7o8peiulh4/Screenshot%202015-02-10%2019.28.16.png?dl=0

When I open Starcheat and load a character with the item in my inventory, Starcheat refuses to open and I get the error I listed in the original bug post.
https://www.dropbox.com/s/s1wstwu7rmlrg9i/Screenshot%202015-02-10%2019.28.46.png?dl=0

**Comment by wizzomafizzo** [comment]
thank you! very thorough. unfortunately these are the exact steps i took and got no errors :(

could you paste the errors that appear in the crash dialogs here? at least the first and last one i see in the images look different to what you pasted in the original bug report

**Comment by FoggyPaws** [comment]
The first error I get (When closing the Raw JSON editor)

**Comment by chrmoritz** [comment]
Could you please try out [version 0.19.1](https://github.com/wizzomafizzo/starcheat/releases/tag/0.19.1) which should at least fix the issue you have posted above.

**Comment by FoggyPaws** [comment]
Just gave it a try, no crashes to be found, at least not following the same steps I did before.
I hadn't seen that the version was 0.19.1, the main page at starcheat.org still says 0.19 so I assumed it hadn't updated.

(The main page still links to 0.19)

**Comment by wizzomafizzo** [comment]
sorry i should have mentioned last night i actually managed to reproduce this, some replace things didn't trigger some did. i will have another crack at it tonight

**Comment by wizzomafizzo** [comment]
ok nevermind, all works now (was there a commit i missed?) anyway may as well wait for someone else to report if it even exists anymore as an issue

**Comment by chrmoritz** [comment]
yeah you missed my commit referenced above 28ddad3, which fixed this (functional scopeing works in JavaScript but not Python)
