### ISSUE TITLE
[SBBF] About handling sbbf02

### ISSUE THREAD

**Issue by chrmoritz** [wizzomafizzo/starcheat#153]
We should definitely handle the sbbf02 format in mods better.

Are mods in sbbf02 format still supported by Starbound.
* If yes we should change to assert in py-starbound to accept /sbbf0[2-3]/
* If no we should catch the exception and just skip the mod and maybe inform the user that they have an outdated mod with name foo in there mods folder

**Comment by wizzomafizzo** [comment]
https://github.com/blixt/py-starbound/commit/4ae3012e324e0c178c48b1609bf7c21299e75f40

**Comment by wizzomafizzo** [comment]
https://github.com/blixt/py-starbound/issues/26 (and this although no progress afaik)

there was also a commit log i saw a while ago saying there were some differences in the format, but i think it only applied to the world files

**Comment by chrmoritz** [comment]
or just
 ```python
header = stream.read(6)
assert (header  == b'SBBF02' or header  == b'SBBF03'), 'Invalid file format'
```

**Comment by wizzomafizzo** [comment]
works for me :+1:

**Comment by wizzomafizzo** [comment]
do you have any example packed files i can test with?

**Comment by chrmoritz** [comment]
Either this https://github.com/wizzomafizzo/starcheat/issues/126#issuecomment-73412753 or create your own with an older copy of Starbound.

**Comment by wizzomafizzo** [comment]
okay i'm gonna get the fork updated and add those log entries tonight. wanna do a hotfix release afterwards so we can knock those tickets out?

**Comment by wizzomafizzo** [comment]
ok logging is updated to make things easier, assert is updated in my py-starbound fork. i didn't update the submodule thing cause i'm still friggin useless at git, will check it in the morning probably

i'm gonna look at next the render_player error and the json thing once i can reproduce/get the errors. if you think we should do a release before then i'm totally happy to
