### ISSUE TITLE
Crashing when open

### ISSUE THREAD

**Issue by 4679** [wizzomafizzo/starcheat#157]
http://pastebin.mozilla.org/8714671
Archlinux i686
Linux 4679-pc 3.18.7-1-ck #1 SMP PREEMPT Wed Feb 11 15:41:22 EST 2015 i686 GNU/Linux

**Comment by wizzomafizzo** [comment]
hi. would you be able to pastebin your starcheat.log as well. it should be in ~/.starcheat

**Comment by wizzomafizzo** [comment]
i think this is the same error as #137 ?

@4679 please see if starcheat works with no mods installed so we can rule those out

**Comment by chrmoritz** [comment]
@4679 Why did you close this? We are aiming to support mods as long as they are not broken. We should probably reopen the issues if this issue was caused by a mod which is not known to be broken and please upload your starcheat.log in this case.

**Comment by 4679** [comment]
My hard disk is broken and starcheat.log is lost
