### ISSUE TITLE
Characters with the same name don't list properly.

### ISSUE THREAD

**Issue by Scynix** [wizzomafizzo/starcheat#162]
I tend to name all my characters the same (for multiplayer), which isn't an issue as far as Starbound is concerned, but starcheat can't list more than one character per name.

**Comment by wizzomafizzo** [comment]
hi. have you tried it with the latest 0.20 release? it only just came out, but i added a specific piece of code which should have allowed characters with the same name

**Comment by chrmoritz** [comment]
@wizzomafizzo: You should change the link on starcheat.org to either point to [all releases](https://github.com/wizzomafizzo/starcheat/releases) or to the [latest redirect](https://github.com/wizzomafizzo/starcheat/releases/latest) instead of a specific tag.

**Comment by wizzomafizzo** [comment]
oh ya good idea. i'll update it soon!

**Comment by Scynix** [comment]
I can confirm it still happens in 0.20. In order for all of my characters to show up I have to change their names to something different.

**Comment by wizzomafizzo** [comment]
ah man that sucks, i wonder why it didn't work :/
i will look into it and let you know, probably won't be a huge fix

**Comment by wizzomafizzo** [comment]
should be fixed in the next release

**Comment by chrmoritz** [comment]
@Scynix Does [starcheat 0.21](https://github.com/wizzomafizzo/starcheat/releases/tag/0.21) fixes this issue for you?
