### ISSUE TITLE
movementcontroller not updating

### ISSUE THREAD

**Issue by FanatiG** [wizzomafizzo/starcheat#163]
After today's update i can't edit character params anymore(like speed, multijump and etc), starcheat just don't see them. Can you fix it please?

**Comment by wizzomafizzo** [comment]
are you talking about the movementcontroller edit button on the tech window or something else?

**Comment by wizzomafizzo** [comment]
ok i see. newly created characters in the latest starbound update only make a stripped down version of the movement controller. will need to do more testing later but i assume adding the old values back in like multijump should work fine?

**Comment by FanatiG** [comment]
"adding the old values back in like multijump should work fine" no, they still don't work even if i type em manually

**Comment by wizzomafizzo** [comment]
i'll have to do a little more testing but honestly i don't think it's going to turn out good :( probably going to be RIP for this feature

i expect they've changed it so you can't just set stuff in it anymore, it's constantly updating and validating itself based on your equipped techs or items. this is exactly how things like active status effects work and why you can't edit those either

**Comment by wizzomafizzo** [comment]
ok looks like it's not used for techs at all now, what's in there is everything that can be and it is constantly updated making it useless to edit

i'll put in a patch to remove the button and dialog. editing would still be possible by exporting the JSON files and editing that but not really any point now

**Comment by wizzomafizzo** [comment]
and it's gone :(

thanks for the report!
