### ISSUE TITLE
Learning techs bug.

### ISSUE THREAD

**Issue by TheUgly** [wizzomafizzo/starcheat#164]
After using "learn all tech" and saving character i've noticed that not all of techs are available. For example in "body" category the only available ones were "energy dash" and "ftl boost". Other techs, like health and energy regen don't show up, like they're not even discovered yet. Same goes for any techs from mods like "xs corporation mechs" - they are present in starcheat, labeled as "enabled", but not appearing in the game. Tested this bug with two characters - same results. Tried to learn techs one by one, but got stuck with the same result - no ingame appearance.
Right now i'm running latest stable version, which was updated 17.02, and using starcheat v0.20

**Comment by wizzomafizzo** [comment]
ahhh cool thanks for confirming this, i wasn't sure if it was actually the case or i was just bad at counting techs

i think this may be related to starcheat's lazy way of generating matching tech module names, although i'm surprised starbound handles it without crashing. can't say when a fix will be in but it's pretty high priority

**Comment by wizzomafizzo** [comment]
[22:25:15.181] Error: Could not instantiate item '[humanjeepTech, 1, {}]'. (ItemException) No such item 'humanjeepTech'
[22:25:15.182] Error: Could not instantiate item '[humanmechTech, 1, {}]'. (ItemException) No such item 'humanmechTech'
[22:25:15.182] Error: Could not instantiate item '[lightrigTech, 1, {}]'. (ItemException) No such item 'lightrigTech'

**Comment by wizzomafizzo** [comment]
okay i see how this works. dashTech just happens to match with its techitem id. humanjeepTech is just humanjeep, humanmechTech is humanMechTech etc and they all work

**Comment by wizzomafizzo** [comment]
okay look out for the next release, should be fixed in there. i can confirm all techs can now be learned and have seen no crashes so far when equipping them

**Comment by chrmoritz** [comment]
@TheUgly This should be fixed now in [starcheat 0.21](https://github.com/wizzomafizzo/starcheat/releases/tag/0.21). Please tell us if you have still issues.
