### ISSUE TITLE
Tech crash

### ISSUE THREAD

**Issue by PwnerPro** [wizzomafizzo/starcheat#165]
http://pastebin.com/vaP4ni2z
Also, before crashing my char doesn't show up in starbound. I think its bc I made myself get a tech that I didn't have which I believe is why it crashes
Also, I have not all the techs when doing Learn All Techs

**Comment by wizzomafizzo** [comment]
hi. the part about not having all the techs enabled is known already but not the crash you got. do you use any mods that provide techs? could you also pastebin a copy of your starcheat logs? https://github.com/wizzomafizzo/starcheat/wiki/help#how-to-get-logs

**Comment by PwnerPro** [comment]
Ok, and no I only have the yarn spinner mod and some song packs.

**Comment by wizzomafizzo** [comment]
could i still get a copy of your log please

**Comment by wizzomafizzo** [comment]
and the player file this is happening with if possible

**Comment by PwnerPro** [comment]
https://www.mediafire.com/?yazai4k8jd2a3dr < Log
and how do I find my char file?

**Comment by chrmoritz** [comment]
It's in `C:\Program Files (x86)\Steam\SteamApps\common\Starbound\giraffe_storage\player\`

**Comment by wizzomafizzo** [comment]
@PwnerPro are you totally sure you're updated to the latest version of starcheat? your logs say 0.18.1 but you should be using 0.20

you can check in Help > About dialog in starcheat

**Comment by PwnerPro** [comment]
Right, I downloaded it from a 3rd party so ill go update

**Comment by chrmoritz** [comment]
your issue should be fixed since version 0.19

**Comment by wizzomafizzo** [comment]
@PwnerPro give us a shout if it's still not working but i'm gonna close this off now. i'm pretty sure updating to the latest version should have fixed things for you
