### ISSUE TITLE
Crash problem with version 0.21

### ISSUE THREAD

**Issue by AmericanTrailMix** [wizzomafizzo/starcheat#172]
When I first launched the program, a popup showed up asking if a directory was the correct directory. I clicked yes (because I thought it was, but it wasn't) and then it tried to put me in the program. It crashed.

I know the cause of the problem is the directory, but I can't change the directory because the program crashes on startup. As I know, this problem is unfixable, so any help would be really nice. Thanks.

**Comment by chrmoritz** [comment]
[reset your settings](https://github.com/wizzomafizzo/starcheat/wiki/help#reset-all-settings)
