### ISSUE TITLE
Norton and Avast antivirus saying Starcheat-0.21 is a virus!

### ISSUE THREAD

**Issue by PwnerPro** [wizzomafizzo/starcheat#175]
I need this fixed asap :/

**Comment by wizzomafizzo** [comment]
Can you please check exactly what it says about it like what virus type it's being categorized as?

**Comment by PwnerPro** [comment]
Ok, ill get a screenshot of those two.

**Comment by PwnerPro** [comment]
http://prntscr.com/6ta1pw this is what it says for norton.

**Comment by wizzomafizzo** [comment]
Is it still doing this with the latest version 0.22? And if possible can you test with both 32 and 64 bit downloads

**Comment by wizzomafizzo** [comment]
You can try again with the latest release and see if it still does this. If it does though there's not really anything I can do besides let the cx_freeze project know Avast is doing this or submit a report to Avast/Norton which could take months for each version.
