### ISSUE TITLE
Random generated items

### ISSUE THREAD

**Issue by FanatiG** [wizzomafizzo/starcheat#188]
This is what i have when i try to spawn random hammers(2 common and 2 uncommon):
![generatedhammers](https://cloud.githubusercontent.com/assets/11052469/7446742/0559568c-f1eb-11e4-8f63-dd5365b15573.PNG)

**Comment by FanatiG** [comment]
i use last version of starcheat and my game version is spirited giraffe - update 4

**Comment by wizzomafizzo** [comment]
Hi. What exactly is the problem you're referring to? If it's the fact they all look the same, starcheat doesn't make any effort to randomly pick images for any swords. Hopefully will in the future.

**Comment by FanatiG** [comment]
the problem is that they look the same in the game too(in inventory and in hands)

**Comment by wizzomafizzo** [comment]
Can you try the latest release and let me know if that looks better. Generated items now pick a random image.

**Comment by wizzomafizzo** [comment]
Let me know if it's not working and I'll reopen
