### ISSUE TITLE
trouble modding armor

### ISSUE THREAD

**Issue by KillTech** [wizzomafizzo/starcheat#190]
I had armor with 30000 stats and the fire hammer had was still killing me so i edited new armor with starcheat giving stats 3 million, I no longer die in game but i can only shoot my modded gun 1 time every few seconds because every bullet completely empty's my energy when i have an armor set with 3 milion in energy stats for all 3 armor. I have the latest version(22)

**Comment by wizzomafizzo** [comment]
hi. it would be helpful if you can post an export of the items that you're talking about, i can see if there are any obvious issues. i can't make any promises though sorry this sounds like a modding/starbound issue more than anything

**Comment by wizzomafizzo** [comment]
Please reply if you need this reopened but I don't think it can be fixed from the starcheat side
