### ISSUE TITLE
maleframes and femaleframes not working?

### ISSUE THREAD

**Issue by Unibu** [wizzomafizzo/starcheat#195]
When I picked some starter armor and tried to edit the frames, nothing happened. I actually tried to switch them to be specific, make it so that when it wants to load male frames, it would load female frames and when it wants to load female frames, it would load male frames. Is this not working in a current version of starcheat or is it a bug?

**Comment by wizzomafizzo** [comment]
Hi. What exactly do you mean by nothing happens? starcheat reverts the change or Starbound just doesn't do what you're expecting? Also, could you please post an example JSON export of the item you're talking about (edited).

I can't say for sure until I get more info but off the top of my head this is probably an issue with Starbound itself. starcheat doesn't really care about what you put in those keys besides showing the player preview.

**Comment by Unibu** [comment]
Lets say I may have done it wrong completely, there are items that look like a skirt on female characters but when male character equips it, it looks like pants, so my goal is to make it look like a pants for both males and females, make it so that it will use the male frames while character is female. Is that what the maleframes and femaleframes are for?

**Comment by wizzomafizzo** [comment]
That is how it works as far as I knew. This has really turned into a modding question, but could you also comment with a copy of the item you're trying to make work (right-click > edit JSON) and I can see if there's anything wrong with it. Can't make any promises though sorry I don't do any modding.

**Comment by Unibu** [comment]
Well, I tried switching the maleframe and femaleframe with each other and it basically does nothing, it does not change how the items look on characters. Not in starcheat, not even in the game. The changed lines are there but it simply does nothing to the item.

example: https://mega.co.nz/#!HF0wCZ5K!W2d5_HEYCQcg6_eyxsWvAeL_3knmpitdpyKrSzMvcQI

**Comment by wizzomafizzo** [comment]
Just had a look. The reason starcheat isn't rendering it properly is because I was lazy and hardcoded the image names, so it doesn't actually make a difference changing the key inside.

As for Starbound not showing it either, I can't really explain that, everything looks as it should be. It might be the case that the devs hardcoded this on their end too but I couldn't tell you for sure. It might be a good idea to check in with some other modders or the devs themselves about how it works.

**Comment by Unibu** [comment]
allright, thanks then.

**Comment by wizzomafizzo** [comment]
np. sorry i couldn't be of much help
