### ISSUE TITLE
I get an IndexError everytime I load up StarCheat

### ISSUE THREAD

**Issue by thakyZ** [wizzomafizzo/starcheat#197]
This is the error I get every time I load up star StarCheat:   
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 180, in __init__
  File "build\gui\mainwindow.py", line 548, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 93, in get_players
  File "build\assets\species.py", line 335, in render_player
  File "build\assets\species.py", line 241, in render_chest
  File "build\assets\images.py", line 27, in get_image
IndexError: list index out of range
It happened after I re-scanned for assets.
EDIT: I looked at the logs I now know why but you may want to exclude the program to search folders that have the name .git because that was the cause...
EDIT: Never mind I found out I had the wrong log here is the new one: http://pastebin.com/3VxPYCLs

**Comment by wizzomafizzo** [comment]
Hi. Thanks for the log, very helpful. Could I also get you to upload a copy of this player: 0033eacfc049eff92f18ac74c27c8f82.player

I suspect this is happening because of a mod not quite following the rules for chest armour, but I'll need to double check in that. Could you also try remove all your mods temporarily, do a re-scan and then see if it works again.

**Comment by thakyZ** [comment]
here is the player https://dl.dropbox.com/s/5q74wm2vq5r0ghw/d99777ca6c58701a3619fb9e90a965ce.player

**Comment by wizzomafizzo** [comment]
thanks for all your investigating dude much appreciated. it looks like when i tried to fix the bug last release i didn't quite catch all of it, so this is probably the same issue. i didn't have any examples to reproduce it before so this is good

i'll keep ya up to date on it all, i wanna try fit a few fixes in the next release so i'm not spamming people with updates but it shouldn't be too long

**Comment by thakyZ** [comment]
No problem! I am glad to help and I would love to be kept up to date since this is the only cheat utility that I like (and I have used every one that has come and gone) and I don't even always use this to cheat I a lot of times use it to look up items! So anyways thanks for making this and I hope you can get the fixes in soon :smile:

**Comment by wizzomafizzo** [comment]
might be back at square one :( i cannot reproduce a crash from those player files

![screen shot 2015-05-31 at 12 56 33 pm](https://cloud.githubusercontent.com/assets/442478/7900604/b05ec8e6-0794-11e5-8b72-275b64acfbd9.png)
![screen shot 2015-05-31 at 12 57 15 pm](https://cloud.githubusercontent.com/assets/442478/7900605/c66786d2-0794-11e5-9c42-29511a6f36b8.png)

i will keep playing around

**Comment by djDarkX** [comment]
I noticed that Ningen mod items cause this kind of crash.  I have a Kemono character and while I had on a vanity item from that mod on the character, it would crash but as soon as I took only that off, it would load.  If you'd like the .player file with the mod item in question, let me know and I'll put it up on my Dropbox for you.

**Comment by thakyZ** [comment]
Well you could try using my [mod pack](https://github.com/thakyZ/LillyPak-Starbound/tree/dev) I am currently reinstalling StarCheat to see if anything changes and I'll let you know...

**Comment by wizzomafizzo** [comment]
is it a specific vest insert? i tried a few of them and still no issues (besides them not showing at all, is that normal?)

python version shouldn't really matter but i haven't tested on windows yet, i'll try give that a shot

i'll check out the ningen mod items too

sorry this one is taking so long guys, but it's hard to fix until i can reproduce the error myself

![screen shot 2015-06-01 at 10 43 34 am](https://cloud.githubusercontent.com/assets/442478/7905424/14432094-084b-11e5-9ae9-f18c13f1bef6.png)

**Comment by wizzomafizzo** [comment]
@djDarkX where is the ningen mod? i can't find it on the site

**Comment by thakyZ** [comment]
The vest insert that I was using was the iron one...

**Comment by djDarkX** [comment]
Ningen Race Mod: http://community.playstarbound.com/resources/ningen-race-mod.191/

It also comes with custom weapons and vanity.  The vanity seems to be what it causing the issues for me.

**Comment by JimClonk** [comment]
Could it be as simple as the program not finding the correct files because it is looking for either male or female versions, but not unisex versions of armour graphics?

**Comment by wizzomafizzo** [comment]
Hi guys could you please confirm if the newest release (0.25) fixes this? I've added a workaround so it should no longer crash the whole app, it just ignore the item instead, but I'd still like to know which items don't show so I can eventually put in a real fix.

**Comment by djDarkX** [comment]
Worked for me.  Item from Felin Costumes+, which is Cat Ears, that is equipped on a Glitch female was causing the crashes if it was equipped and with the new version, it just doesn't show on the preview and is still equipped.  So I can confirm, so far, that the work around did the trick.

**Comment by wizzomafizzo** [comment]
sweet, thanks for testing. are you talking about these ears?
![screen shot 2015-06-06 at 10 55 18 pm](https://cloud.githubusercontent.com/assets/442478/8020093/27619fae-0c9f-11e5-8884-4d7ada0ea15d.png)

**Comment by djDarkX** [comment]
That's correct.  If I had it equipped, it would crash the program, but when unequipped, it worked.  At least now I don't have to worry about that. lol
