### ISSUE TITLE
When i try to assign a custom made png to an item it leaves it blank

### ISSUE THREAD

**Issue by EzTapia** [wizzomafizzo/starcheat#202]
So i recently made a mask and here it is
![head](https://cloud.githubusercontent.com/assets/13026212/8368547/a36a83ac-1b60-11e5-8198-0086409feb4c.png)
And i put the folder path into the image browser and nothing came up and by the way it's a png file and it's 86 by 215 pixels, so am i doing it wrong? do i have to put it into the starbound directory? Does it have to be 16 by 16?I don't know that much about starcheat... please answer as soon as possible

**Comment by wizzomafizzo** [comment]
even if it's just a single image it needs to be packaged as a mod before either starbound or starcheat can see and use it. i'm not sure if 16x16 is a strict requirement either but it's going to almost not show up if you leave it the current size too

**Comment by EzTapia** [comment]
How do you package it as a mod?
