### ISSUE TITLE
Editing grappling hooks has no effect on the item what-so-ever

### ISSUE THREAD

**Issue by Angelite191** [wizzomafizzo/starcheat#215]
![](http://i.imgur.com/5aNRLOn.png)
According to the JSON parameters, the handle should be a hook and the line should be a solid black. instead it remains unchanged. Changing the hands from 1 handed to 2 handed works fine, along with changing the descriptions, but ammo usage doesn't seem to change either. I have no idea what would make grappling hooks of all things immune to editing.

**Comment by wizzomafizzo** [comment]
when you say it remains unchanged does that mean you change it, save it and after you open the save in starbound it rewrites the colour back to its original value?

very likely i've just messed up the internal item version starbound uses again, and it's running its item conversion process to "upgrade" it to the correct version

**Comment by Angelite191** [comment]
It doesn't rewrite, it just doesn't apply. So if I change the colors, it'll save on the file, but it won't show in game. When I go back to the file, it still shows the changes. 

Just looks like starbound isn't reading the changes.

**Comment by Xirukai** [comment]
Starbound calls the stuff automatically from the item files. If the item is static, changing it wont have any effect. Some variables a hard-coded. The only way to change this is to edit the item itself. Which is a JSON too. Others may or may not be able to see your changes.

**Comment by darkvode** [comment]
easyest way to do it is to make a replacer mod
