### ISSUE TITLE
How to make a glow armor

### ISSUE THREAD

**Issue by zzzsennn** [wizzomafizzo/starcheat#219]
I'd like a glow armor.What should I do? When i Input ”stat“: "glow". Will become perfectly generic item.

**Comment by plmanith17** [comment]
Hmm maybe try putting it directly under statusEffects, like "statusEffects": [ "glow", ] instead. If it works, some other notable attributes are thorns,rage,bandage6,nova,lowgrav. Alternate glow effects could be xenonglow,halogenglow,lanternglow.

**Comment by zzzsennn** [comment]
Thank you

**Comment by zzzsennn** [comment]
But armor can’t Increase energy.

**Comment by plmanith17** [comment]
hmm do you mean energy itself or energy regen? Energy itself should be be under "statusEffects": [ {"amount":___, "stat": "maxEnergy"}

**Comment by zzzsennn** [comment]
Thank you!

**Comment by chrmoritz** [comment]
Looks like everything was answered here. If you still have questions about this feel free to reopen the issue.

**Comment by wizzomafizzo** [comment]
good idea for a label

**Comment by chrmoritz** [comment]
@wizzomafizzo thats one of the default labels, I only started using it.
