### ISSUE TITLE
How to edit light color？

### ISSUE THREAD

**Issue by zzzsennn** [wizzomafizzo/starcheat#221]
How to edit light color？for example，Glow attribute emanatory light。

**Comment by plmanith17** [comment]
Unfortunately, I don't think it's possible (well at least I think so...), mainly because armor uses the .statuseffect file, which does not have the actual code for colors as it's in the .lua file. Only flashlight colors are changeable since the color attribute is in the code directly.

**Comment by zzzsennn** [comment]
Thank you all the same
