### ISSUE TITLE
Issue regarding morphball

### ISSUE THREAD

**Issue by TheHalfSaneMagician** [wizzomafizzo/starcheat#222]
It seems as though editing you character physically creates a bug in which u go into the morphball your character does not hide in the morph ball.  Instead it kinda just hangs there

Proof:
http://steamcommunity.com/sharedfiles/filedetails/?id=516012931

P.S
I also made a new character without changes apearance wise and it was hidden when I went into the morph ball

**Comment by wizzomafizzo** [comment]
hi. could you upload a copy of your player file that this happens with

**Comment by TheHalfSaneMagician** [comment]
I cant anymore.  It seems as though after changing my character again, it fixed itself.  If it does happen again I will gladly post the file. :)
