### ISSUE TITLE
Manage techs

### ISSUE THREAD

**Issue by wizzomafizzo** [wizzomafizzo/starcheat#23]
Should be able to manage techs. We don't have support for reading techs from the saves yet. Wait until next patch, should be easier.

**Comment by emersound** [comment]
> Should be able to manage techs. We don't have support for reading techs from the saves yet. Wait until next patch, should be easier.

10 years later...  crickets.

**Comment by wizzomafizzo** [comment]
> > Should be able to manage techs. We don't have support for reading techs from the saves yet. Wait until next patch, should be easier.
> 
> 10 years later... crickets.

Wow, what a rude comment to make! I expect you to submit a patch for this shortly since it must be so simple

**Comment by emersound** [comment]
Sorry, clearly not so simple.  I was just hoping someone would have an answer, I looked everywhere but this thread was the only one that described my issue.
