### ISSUE TITLE
Stats reseting

### ISSUE THREAD

**Issue by VyroKyro** [wizzomafizzo/starcheat#230]
In the new update I have been trying for hours trying to find out what I was doing wrong. I know how to edit everything perfectly fine but when I load the game the Stats are reset.

**Comment by wizzomafizzo** [comment]
i am doing another check tomorrow to make sure it isn't starcheat messing things up but it's sounding like they're locked down from editing. i know this has been the case in the past for the matter manipulator

**Comment by VyroKyro** [comment]
Ok Thx

**Comment by wizzomafizzo** [comment]
have you had any luck since the latest starcheat release? there was something i changed that would have made items reset before

**Comment by wizzomafizzo** [comment]
closing for now. please let us know if this issue is still happening and i will reopen
