### ISSUE TITLE
(Not an issue) Build Artifacts

### ISSUE THREAD

**Issue by laz2727** [wizzomafizzo/starcheat#233]
Just a reminder that there's no need to build from source, appveyor build artifacts work acceptably well.

**Comment by wizzomafizzo** [comment]
hi. could you elaborate a bit? i gotta be honest i still can't figure out what this is about

**Comment by laz2727** [comment]
Your readme says that you have to build from source if you want to use latest Starcheat. However, there's no need to do that, because appveyor automatically builds all commits and you can download the results(click on any job, click artifacts)

**Comment by chrmoritz** [comment]
Thats not true. Until today Appveyor was only triggered by tags = releases and in some rare exceptions manually triggered builds.

I've improved our CI with nightly builds and a corresponding doc change today, which was landed in dev. So you will able to get snapshots for prereleases starting now for the next release, but you weren't able to get these in the past.
