### ISSUE TITLE
New Stable is out

### ISSUE THREAD

**Issue by Xirukai** [wizzomafizzo/starcheat#234]
Gonna try whats working and what isnt, if it plainly crashes upon startup I'll post the error log.

**Comment by Xirukai** [comment]
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 180, in __init__
  File "build\gui\mainwindow.py", line 547, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 107, in get_players
  File "build\assets\species.py", line 338, in render_player
  File "build\saves.py", line 692, in get_visible
KeyError: '__content'

This is what I get.

**Comment by wizzomafizzo** [comment]
Dump of latest player file: http://pastebin.com/rXhwXL6E

Metadata file also seems to have changed. There's just a single file now, haven't looked into it yet.

Full error:
Traceback (most recent call last):
  File "./build/starcheat.py", line 83, in <module>
    main()
  File "./build/starcheat.py", line 80, in main
    gui.mainwindow.MainWindow()
  File "/Users/callan/dev/starcheat/build/gui/mainwindow.py", line 180, in __init__
    open_player = self.open_file()
  File "/Users/callan/dev/starcheat/build/gui/mainwindow.py", line 547, in open_file
    character_select = CharacterSelectDialog(self, self.assets)
  File "/Users/callan/dev/starcheat/build/gui/openplayer.py", line 58, in __init__
    self.get_players()
  File "/Users/callan/dev/starcheat/build/gui/openplayer.py", line 107, in get_players
    preview = self.assets.species().render_player(player)
  File "/Users/callan/dev/starcheat/build/assets/species.py", line 339, in render_player
    chest_slot = player.get_visible("chest")
  File "/Users/callan/dev/starcheat/build/saves.py", line 694, in get_visible
    return main["__content"]
KeyError: '__content'

**Comment by wizzomafizzo** [comment]
New item format is causing this specific issue:

{
                  "id" : "Item",
                  "version" : 7,
                  "content" : {
                      "parameters" : {
                          "colorIndex" : 413676287
                      },
                      "count" : 1,
                      "name" : "floranleafchest"
                  }
              }

**Comment by wizzomafizzo** [comment]
Ok so new commit is now in dev that makes things load and save again.

These issues still exist though:
- [ ] Metadata file has moved and may no longer contain anything interesting
- [ ] Quests have moved to save file, currently can't be edited
- [ ] Same with ship upgrades
- [ ] Major graphic glitches when editing appearance
- [ ] Object bag not displaying (but there was a pull request for it I think?)

**Comment by Xirukai** [comment]
New item make-up for random-generated guns.

{
  "itemName" : "commonpistol",
  "price" : 120,
  "maxStack" : 1,
  "rarity" : "common",
  "description" : "Pop pop",
  "shortdescription" : "Common Pistol",
  "tooltipKind" : "gun",
  "weaponType" : "Pistol",
  "twoHanded" : false,
  "itemTags" : ["weapon","ranged","pistol"],
  "level" : 1,

  "animation" : "/items/active/weapons/ranged/gun.animation",
  "animationParts" : { },
  "animationCustom" : { },
  "baseOffset" : [-0.25, 0.25],
  "muzzleOffset" : [0,0.375],

  "scripts" : ["/items/active/weapons/ranged/gun.lua"],

  "elementalType" : "physical",

  "primaryAttack" : {
    "fireTime" : [0.33, 1.0],
    "baseDps" : [3.75, 4.5],
    "energyUsage" : [11.25, 13.5],
    "inaccuracy" : 0.025,

    "projectileType" : "standardbullet",
    "projectileParameters" : {
      "knockback" : [4,8]
    }
  },
  "fireSounds" : [ "/sfx/gun/pistol1.ogg", "/sfx/gun/pistol2.ogg", "/sfx/gun/pistol3.ogg", "/sfx/gun/pistol4.ogg" ],

  "stances" : {
    "idle" : {
      "armRotation" : 0,
      "weaponRotation" : 0,
      "twoHanded" : false,

      "allowRotate" : true,
      "allowFlip" : true
    },
    "fire" : {
      "duration" : 0,
      "armRotation" : 10,
      "weaponRotation" : 10,
      "twoHanded" : false,

      "allowRotate" : false,
      "allowFlip" : true
    },
    "cooldown" : {
      "duration" : 0.15,
      "armRotation" : 10,
      "weaponRotation" : 10,
      "twoHanded" : false,

      "allowRotate" : false,
      "allowFlip" : true
    }
  },

  "builder" : "/items/buildscripts/buildweapon.lua",
  "builderConfig" : [{
    "nameGenerator" : "pistolnames.config:nameGen",
    "animationParts" : {
      "butt" : {
        "path" : "/items/active/weapons/ranged/pistol/butt/<variant>.png",
        "variants" : 20,
        "paletteSwap" : true
      },
      "middle" : {
        "path" : "/items/active/weapons/ranged/pistol/middle/<variant>.png",
        "variants" : 20,
        "paletteSwap" : true
      },
      "barrel" : {
        "path" : "/items/active/weapons/ranged/pistol/barrel/<variant>.png",
        "variants" : 20,
        "paletteSwap" : true
      },
      "muzzleFlash" : "/items/active/weapons/ranged/muzzleflash.png"
    },
    "gunParts" : ["butt", "middle", "barrel"],
    "altAbilities" : [ ],
    "palette" : "/items/active/weapons/colors/ranged.weaponcolors",
    "iconDrawables" : ["butt", "middle", "barrel"]
  }]
}

**Comment by Xirukai** [comment]
I got some of the new random-genned weapons in my inventory. When Starcheat is able to start-up and read player files again I'll try to see whats what. Since the code I pasted was from the base item itself. Will report back on this post when it does.

**Comment by wizzomafizzo** [comment]
Ok that object tab patch is merged and I've move all the metadata stuff back to player. Ship editing works but quests have been changed significantly so that's still broken. If that's the only thing that's broken then maybe we consider releasing a hotfix with that button disabled.

@Xirukai could you please test something for me? Does dragging and dropping items on Windows slow things down?

Also with the random generated items, are they broken too?

**Comment by Xirukai** [comment]
@wizzomafizzo got a packed zip file with the build exe in it? Dont got python on my PC.

**Comment by Xirukai** [comment]
@wizzomafizzo You'll find my email at my profile now, forgot to set that to public.

**Comment by Xirukai** [comment]
@wizzomafizzo Scrap that, got a working python envoirement with all the prerequisites working.

Built a standalone distribution and I get this error. Both from Dev and Master under Windows. When it is reading the player files.

[ Traceback (most recent call last):
  File "E:\Python\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
    exec(code, m.__dict__)
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 180, in __init__
  File "build\gui\mainwindow.py", line 547, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 107, in get_players
  File "build\assets\species.py", line 338, in render_player
  File "build\saves.py", line 697, in get_visible
KeyError: 'content' ]

**Comment by wizzomafizzo** [comment]
@Xirukai how's the new version going for you?

**Comment by wizzomafizzo** [comment]
still have a report of it freezing half way (no error message) but other people are working now

**Comment by Xirukai** [comment]
Mine is working perfectly fine. @wizzomafizzo , no issues. Apart from the random-genned items spawned in SC not generating properly. The tiered stuff spawns okay, no issues with that. Experienced no half-way freezes either.

**Comment by wizzomafizzo** [comment]
moved unchecked issues to new ticket
