### ISSUE TITLE
i keep crashing can anyone help? O:

### ISSUE THREAD

**Issue by ReyDuece** [wizzomafizzo/starcheat#243]
sit down and get a cup of hot chocolate because heres the story

so i tried opening starcheat and it crashed so i decided to delete all my characters and make a new one and it still crashed can anyone help o:? heres the error

raceback (most recent call last):

File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>

File "build\starcheat.py", line 83, in <module>

File "build\starcheat.py", line 80, in main

File "build\gui\mainwindow.py", line 176, in __init__

File "build\gui\mainwindow.py", line 542, in open_file

File "build\gui\openplayer.py", line 58, in __init__

File "build\gui\openplayer.py", line 107, in get_players

File "build\assets\species.py", line 339, in render_player

File "build\saves.py", line 622, in get_visible

KeyError: 'content'

i have  re-installed the game , deleted all backups , characters , mods , has updated sb to glad giraffe and has 0.27 made new character and i still have issues can any one help?

**Comment by wizzomafizzo** [comment]
could you please take a screenshot of the player folder after you get this error. this might be a big problem if it really is happening with newly created players

**Comment by ReyDuece** [comment]
sorry for being a it late his the pic https://gyazo.com/b1413ad7606eb6c25d15be5906fcfce1

**Comment by wizzomafizzo** [comment]
cool thanks. could you also please upload a copy of all 3 player/shipworld/bak files for me, like on dropbox or mega

no rush if it's late, i'll be round tomorrow

**Comment by ReyDuece** [comment]
here (sorry im late again i had to make an account on mega x0x) https://mega.nz/#fm

**Comment by ReyDuece** [comment]
i have found a solution but this is with my new character simply do the first quests and it should be finished but im going to try with my old ones

**Comment by ReyDuece** [comment]
yeah no it doesnt work /:

**Comment by xXAobaXx** [comment]
I have this same issue, I'm guessing that it may have something to do with what's in the current files of the new update of Starcheat. Either the file contains OLD content from the last Starbound update or the lack of content for the new Starbound update. Hope this hypothesis may come in handy Wizz.

**Comment by wizzomafizzo** [comment]
let me know if the latest release works any better. still figuring it out

**Comment by xXAobaXx** [comment]
I have a solution to this problem, go into your player file and empty it comepletely. After that, create a new character. After that choose ONE player file that you want to continue using and Voila. Problem aolved

**Comment by ReyDuece** [comment]
we're making process :D,but it stops responding at 41%

**Comment by wizzomafizzo** [comment]
@ReyDuece could you post a full copy of your log after it happens. you can see how here: https://github.com/wizzomafizzo/starcheat/wiki/help#how-to-get-logs

after that i can see which player file is causing it, then i'll probably get you to upload that player

**Comment by xXAobaXx** [comment]
I just got rid of all of the characters that were old or had weapons that don't exist anymore

**Comment by xXAobaXx** [comment]
It could also be part of the backup files

**Comment by xXAobaXx** [comment]
If that helps out

**Comment by ReyDuece** [comment]
oh wait it does work! good job ^^
