### ISSUE TITLE
Starcheat still crashes because of "invalid" (nighty) saves.

### ISSUE THREAD

**Issue by laz2727** [wizzomafizzo/starcheat#253]
Log: http://pastebin.com/h5XsfhhG

And don't believe it saying "26", it's 27.1.

**Comment by chrmoritz** [comment]
They are changing the player file format again but didn't bumped the format version yet, so the crash is expected behavior atm, see #254

**Comment by laz2727** [comment]
>starcheat now ignores any unsupported save files isntead of crashing

But whatever

**Comment by wizzomafizzo** [comment]
@laz2727 that was in reference to the issue occurring at the time, not everything that could happen in the future
