### ISSUE TITLE
Items in inventory appearing again

### ISSUE THREAD

**Issue by LLIEO7OPAT** [wizzomafizzo/starcheat#256]
Hi. i'm having problem: when I'm exited from the game, my inventory again stuff items.
It occurs every times
[Starbound.pdf](https://github.com/wizzomafizzo/starcheat/files/86114/Starbound.pdf)

PS: Sorry for my bad English

**Comment by Xirukai** [comment]
Be sure to reload your character after exiting starbound, every single time.
Because else it will simply load all the stuff you added or edited from before.

**Comment by LLIEO7OPAT** [comment]
Thanks for the answer. How to reload my character? If reload my character - the button in starcheat (File -> Reload), then reload doesn't help. 
Have to begin new game :\

**Comment by wizzomafizzo** [comment]
the way you should be doing it is:
- make sure starbound is not running
- open starcheat
- edit player
- open starbound
- close starbound
- file > reload in starcheat

is this how you're doing it? if you make any changes with starcheat while starbound is open they won't count

**Comment by wizzomafizzo** [comment]
please let me know if this is still an issue and i will reopen
