### ISSUE TITLE
How to transfer data from one player to another?

### ISSUE THREAD

**Issue by LunarRadiance** [wizzomafizzo/starcheat#257]
While a friend and I were playing my computer crashed which caused my player data to become corrupted. To fix this I had them send me their player file and used starcheat to get most of the stuff I had back. But we just realized now when we play, it won't let us join each other's server since the player files are considered the same. I've changed my character's race and name but since they are the same file we just get kicked out of the other's game.
I was wondering if there was some easy way to transfer all the data from one character to another. Either that or change the UUID. 
![untitled](https://cloud.githubusercontent.com/assets/16656765/12249373/f4e13232-b884-11e5-9dca-93e6a8e64c96.png)

**Comment by Xirukai** [comment]
Export the entire player JSON
Create a new player, export that entire JSON as well.
Loacate the UUID within the JSON of the new one and replace the one found in the original one.
Be sure to also use the new UUID for the ship save.
