### ISSUE TITLE
Crashed after reloading save when picking out save

### ISSUE THREAD

**Issue by Sandblaster** [wizzomafizzo/starcheat#263]
Got a crash whenever reloading (to refresh saves and such) when picking,I hadn't picked one before and Starbound was not open at the time (It was open before I reloaded but not during).
Just adding this,was strange,it went not responding,then crashed (or unresponsive).

**Comment by wizzomafizzo** [comment]
is this still broken? and if so are you able to upload your save files somewhere?

**Comment by wizzomafizzo** [comment]
please let me know if this is still an issue and i will reopen
