### ISSUE TITLE
Starcheat crashes when opening

### ISSUE THREAD

**Issue by aDrunkLittleDerp** [wizzomafizzo/starcheat#268]
Video: https://youtu.be/8Rx6W-3nCWw
My mac verison is OS X 10.8.5.
This happens whenever I try to open Starcheat.
It seems to be missing a module related to showing images.

**Comment by chrmoritz** [comment]
Looks like your OS X version is to old to be compatible with the binary we provide, which is build on OS X 10.9.

But you can try to build it from source on your system: https://github.com/wizzomafizzo/starcheat#mac

**Comment by wizzomafizzo** [comment]
please let me know if this is still an issue and i will reopen
