### ISSUE TITLE
Weapon modification might be broken?

### ISSUE THREAD

**Issue by Chicken-Man** [wizzomafizzo/starcheat#270]
ok so i tried to edit my rocket launcher, i lower the energy consumption factor, and the damage went down. The energy consumption went up for some reason. I edited the rate of fire, but for some reason it doesnt go above 0.9. Whenever i change something it seems like all of the settings get randomized. Am i dumb or is there something that doesnt work right?

**Comment by wizzomafizzo** [comment]
hi, sorry for the delay, would i be able to grab a copy of this save file if you still have it? or at least the id of the weapon you were editing? i've tested a few and haven't had much trouble, i'll keep messing with it though

**Comment by wizzomafizzo** [comment]
please let me know if this is still an issue and i will reopen
