### ISSUE TITLE
Ship capabilities bug

### ISSUE THREAD

**Issue by lofar968** [wizzomafizzo/starcheat#273]
Not sure if this is an actual bug but the only thing I can add when under the Edit List for Capabilities under Ship management is "teleport". I cant seem to add anything else. Am I missing something or is this a missing feature?

**Comment by wizzomafizzo** [comment]
sorry this has taken so long. i've just tried this and although it does keep adding teleport, you can still edit each line. can you try just double clicking on one of the entries? i problem just made it add the last existing capability so it at least had something entered

**Comment by lofar968** [comment]
just tried it and it works fine! that makes a lot of sense. thanks for the help!

**Comment by wizzomafizzo** [comment]
No worries. Sorry again for the wait, let me know if any other issues crop up
