### ISSUE TITLE
Matter Manipulator Color

### ISSUE THREAD

**Issue by JacquesP19** [wizzomafizzo/starcheat#278]
Hello guys, some days ago I chaged my Matter Manipulator color to red, I don't remember how I did it, but now I want change to blue again, can someone help me? (Sorry my english is not very well)

**Comment by wizzomafizzo** [comment]
You can right-click the item in Starcheat and go edit JSON to see all the options that you've customised but I can't give you much more information than that sorry. Might be worth copy and pasting what you see in that dialog here maybe I can give some better insight.

I'm surprised you got it to change colour in the first place though. I was under the impression that the matter manipulator was one of the "locked down" items in the game.

**Comment by JacquesP19** [comment]
Hello, good night

I'm also impresed how I made it, here's the JSON:

{

"count": 1,

"name": "beamaxe",

"parameters": {

"altBlockRadius": 1,

"blockRadius": 4,

"canCollectLiquid": true,

"category": "Tool ^green;[R]",

"description": "Manipulates anything that matters. ^green;Quick select with
[R] key.",

"endImages": [

"/humanoid/any/ball.png",

"/humanoid/any/tileglow.png",

"/humanoid/any/4tileglow.png",

"/humanoid/any/ball.png"

],

"farControlPointElasticity": 0.9,

"firePosition": [

5,

0

],

"fireTime": 0.25,

"firstStripeThickness": 0.05,

"handPosition": [

-2,

0

],

"harvestLevel": 99,

"image": "/humanoid/any/gravgun1.png",

"innerBrightnessScale": 20,

"inventoryIcon": "gravgunicon.png",

"itemName": "beamaxe",

"largeImage": "gravgunlarge.png",

"maxBeamJitter": 0.1,

"maxBeamLines": 5,

"maxBeamTrans": 0.4,

"maxBeamWidth": 4,

"maxStack": 1,

"minBeamJitter": 0.05,

"minBeamLines": 3,

"minBeamTrans": 0.1,

"minBeamWidth": 2,

"nearControlPointDistance": 0.9,

"nearControlPointElasticity": 0.1,

"price": 0,

"rarity": "Uncommon",

"secondStripeThickness": 0.1,

"segmentsPerUnit": 1,

"shortdescription": "Matter Manipulator",

"strikeSounds": [

"/sfx/tools/atom.ogg",

"/sfx/tools/atom2.ogg",

"/sfx/tools/atom3.ogg",

"/sfx/tools/atom4.ogg",

"/sfx/tools/atom5.ogg"

],

"targetSegmentRun": 1,

"tileDamage": 1.3,

"tooltipKind": "tool",

"twoHanded": true

}

}


2016-04-29 3:59 GMT-03:00 Callan Barrett <notifications@github.com>:

**Comment by medeor413** [comment]
I don't see anything in that code that would change the MM's color. If you mean that you changed the highlight color of the MM, that's controlled by the "favorite" color in your character's appearance menu.

**Comment by JacquesP19** [comment]
Thank you, I fixed
Em 17/05/2016 19:25, "medeor413" <notifications@github.com> escreveu:
>
> I don't see anything in that code that would change the MM's color. If
you mean that you changed the highlight color of the MM, that's controlled
by the "favorite" color in your character's appearance menu.
