### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by juhim** [wizzomafizzo/starcheat#286]
Im playing on steam, steam has updated Starbound (Glad Giraffe) to Starbound 1.0 (New Items, etc.). I think its bad version of starcheat (v 0.27), or something, im not missing the msvcr100.dll file. I installed all files needed to make it work. I start it, it says: New assets..., I click search and it will show me this message: Oops, starcheat has crasched. --- To report this error...
Could you help me somehow? or Update starcheat to same version as Starbound 1.0??
Again
-----------------------------------------------------------------------------------------------------------------
-Starbound 1.0
-No Mods.
-All files installed.

**Comment by Hammster** [comment]
1.0 is fresh out, it will take a while till this here is updated.

**Comment by Ambientlight124** [comment]
i have the same issue

**Comment by medeor413** [comment]
Starcheat currently does not support Starbound 1.0. A fix is being worked on, but it could be some time.

**Comment by chrmoritz** [comment]
Closing this in favor of #286 (this is the tracking issue for Starbound 1.0 support).
