### ISSUE TITLE
Remove MenuBar Icons

### ISSUE THREAD

**Issue by kurisubrooks** [wizzomafizzo/starcheat#296]
The items in the app's context menu look ghastly, and break macOS' UX Guidelines. I suggest removing the images altogether. The text need not be changed as I find it already properly descriptive of their actions. 

![image](https://cloud.githubusercontent.com/assets/6291467/17195689/b4ebed1a-54a2-11e6-840a-b68a4cb1932f.png) ![image](https://cloud.githubusercontent.com/assets/6291467/17195562/da607166-54a1-11e6-8f29-920723b78150.png) ![image](https://cloud.githubusercontent.com/assets/6291467/17195702/cd665f42-54a2-11e6-851e-a0374850300d.png)

Refer to the Human Interaction Device Guidelines here:
https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/MenuAppearanceBehavior.html#//apple_ref/doc/uid/20000957-CH23-SW1

**Comment by wizzomafizzo** [comment]
agreed. i've looked into this in the past but left it because it's somewhat hacky. when the mainwindow is initialized we have to just do a loop through the menus and disable the icons

**Comment by wizzomafizzo** [comment]
(i have no issue doing that anymore)

**Comment by kurisubrooks** [comment]
Couldn't you just delete the icon property in Qt Designer?

**Comment by wizzomafizzo** [comment]
Is there a way I'm missing to only remove the properties on a single platform? I would still like them in the Windows build, I think they look fine there and it fits more with Microsoft 's own standards

**Comment by kurisubrooks** [comment]
Hmm, i'm not sure if that's possible through Qt, that'd have to be coded in.

**Comment by chrmoritz** [comment]
There is a [`iconVisibleInMenu`](http://doc.qt.io/qt-5/qaction.html#iconVisibleInMenu-prop) property in QT which is globally settable by [`Qt::AA_DontShowIconsInMenus`](http://doc.qt.io/qt-5/qt.html#ApplicationAttribute-enum). Don't know yet how far this is exposed in pyqt5.

**Comment by chrmoritz** [comment]
It's available in PyQt by calling (on darwin only) [`QCoreApplication.setAttribute `](http://pyqt.sourceforge.net/Docs/PyQt4/qcoreapplication.html#setAttribute) [`(Qt.AA_ImmediateWidgetCreation)`](http://pyqt.sourceforge.net/Docs/PyQt4/qt.html#ApplicationAttribute-enum).

**Comment by chrmoritz** [comment]
Addressed in medeor413#28.

**Comment by chrmoritz** [comment]
FYI: I've added the 1.0 beta as a `devel` version to the [starcheat homebrew formula](https://github.com/chrmoritz/homebrew-starcheat/blob/master/starcheat.rb#L9).
