### ISSUE TITLE
Add Logging to build.py

### ISSUE THREAD

**Issue by kurisubrooks** [wizzomafizzo/starcheat#299]
Currently running build.py doesn't log anyhting if you're not running Windows. Would it be possible to add some basic logging, even just a "Task Complete" or anything to let us know that the build actually succeeded/failed? 

```
~/Developer/starcheat $ ./build.py
~/Developer/starcheat $ 
```

**Comment by medeor413** [comment]
Did you try `./build.py -v`

**Comment by kurisubrooks** [comment]
That's much better. I reckon this should be default.
![image](https://cloud.githubusercontent.com/assets/6291467/17234958/87539fe0-5580-11e6-86f1-8cc6131ddd8c.png)

**Comment by chrmoritz** [comment]
I want to refractor to build system anyway soon, when I find some time. I'll add this to my list:
* default to verbose and a `-q` quite option

**Comment by chrmoritz** [comment]
Addressed in https://github.com/medeor413/starcheat/pull/28. More build system cleanup coming soon.
