### ISSUE TITLE
Fenerox Race not working?

### ISSUE THREAD

**Issue by Septicity** [wizzomafizzo/starcheat#307]
I've seen some people using the penguin race and such, but the Fenerox race just makes starbound seem to not read the player files. Is this a starcheat bug or just starbound being stubborn?

**Comment by kurisubrooks** [comment]
Fenerox were never meant to be a playable race. The option exists in
Starcheat because it pulls all playable and NPC races from the games
assets. Interesting that it just corrupts your player file instead of
crashing the game on load. I don't think we'll take any action for this
one.

**Comment by Septicity** [comment]
Alright, I get that, but isn't that the same with the penguin race?

**Comment by kurisubrooks** [comment]
I would've expected so, but the penguin race was written a long time ago,
probably with an older system. it's been a playable race for a while.

**Comment by Septicity** [comment]
Gotcha.
