### ISSUE TITLE
Starcheat install homebrew fail

### ISSUE THREAD

**Issue by numidark** [wizzomafizzo/starcheat#344]
Hello, starcheat install on homebrew (macos) fail, install not possible : 

```
$ brew install chrmoritz/starcheat/starcheat --devel
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
dmd                        dub                        termius

==> Installing starcheat from chrmoritz/starcheat
==> Cloning https://github.com/medeor413/starcheat.git
Updating /Users/gregory/Library/Caches/Homebrew/starcheat--git
==> Checking out branch master
==> pip3 install Pillow --upgrade
Last 15 lines from /Users/gregory/Library/Logs/Homebrew/starcheat/01.pip3:
  File "/usr/local/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python3.6/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python3.6/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 1] Operation not permitted: '/usr/local/lib/python3.6/site-packages/OleFileIO_PL.py'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/chrmoritz/homebrew-starcheat/issues
```

**Comment by chrmoritz** [comment]
Can't reproduce this issue locally. Looks like you don't have permission to your python3.6 `site-packages` folder.

What is the output of `brew doctor`?
You could try to just reinstall python3 with `brew reinstall python3` and retry to `brew install starcheat --devel` afterwards.
It this doesn't help: What is the output of `ls -la /usr/local/lib/python3.6/site-packages`?

**Comment by numidark** [comment]
Hello chrmoritz, here result of brew doctor

brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  libpng

Warning: /usr/bin occurs before /usr/local/bin
This means that system-provided programs will be used instead of those
provided by Homebrew. The following tools exist at both paths:
  2to3-2.7
  easy_install-2.7
  idle2.7
  info
  infokey
  install-info
  makeinfo
  pydoc2.7
  python2.7
  python2.7-config
  pythonw2.7
  smtpd2.7.py
  texi2dvi
  texi2pdf
  texindex

Consider setting your PATH so that /usr/local/bin
occurs before /usr/bin. Here is a one-liner:
  echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bash_profile

**Comment by numidark** [comment]
You could try to just reinstall python3 with brew reinstall python3 and retry to brew install starcheat --devel afterwards.

Not work

**Comment by numidark** [comment]
ls -la /usr/local/lib/python3.6/site-packages
total 48
drwxr-xr-x  19 gregory  admin   646 16 aoû 12:07 .
drwxr-xr-x   3 gregory  admin   102 29 déc  2016 ..
drwxr-xr-x  97 gregory  admin  3298 29 déc  2016 PIL
drwxr-xr-x  10 gregory  admin   340 29 déc  2016 Pillow-3.4.2.dist-info
drwxr-xr-x  75 gregory  admin  2550 15 aoû 11:19 PyQt5
drwxr-xr-x   4 gregory  admin   136 16 aoû 12:07 __pycache__
-rw-r--r--   1 gregory  admin   126 17 jul 05:45 easy_install.py
drwxr-xr-x  23 gregory  admin   782 16 aoû 12:07 pip
drwxr-xr-x   9 gregory  admin   306 16 aoû 12:07 pip-9.0.1-py3.6.egg-info
drwxr-xr-x   6 gregory  admin   204 16 aoû 12:07 pkg_resources
drwxr-xr-x  35 gregory  admin  1190 16 aoû 12:07 setuptools
drwxr-xr-x   9 gregory  admin   306 16 aoû 12:07 setuptools-32.2.0-py3.6.egg-info
lrwxr-xr-x   1 gregory  admin    64 15 aoû 11:18 sip.pyi -> ../../../Cellar/sip/4.19.3_1/lib/python3.6/site-packages/sip.pyi
lrwxr-xr-x   1 gregory  admin    63 15 aoû 11:18 sip.so -> ../../../Cellar/sip/4.19.3_1/lib/python3.6/site-packages/sip.so
lrwxr-xr-x   1 gregory  admin    69 15 aoû 11:18 sipconfig.py -> ../../../Cellar/sip/4.19.3_1/lib/python3.6/site-packages/sipconfig.py
lrwxr-xr-x   1 gregory  admin    72 15 aoû 11:18 sipdistutils.py -> ../../../Cellar/sip/4.19.3_1/lib/python3.6/site-packages/sipdistutils.py
-rw-r--r--   1 gregory  admin  1980 16 aoû 12:07 sitecustomize.py
drwxr-xr-x  20 gregory  admin   680 16 aoû 12:07 wheel
drwxr-xr-x   9 gregory  admin   306 16 aoû 12:07 wheel-0.29.0-py3.6.egg-info

**Comment by chrmoritz** [comment]
Could you please run `pip3 uninstall Pillow` (confirm the uninstall with `y`) and than `pip3 install olefile Pillow --upgrade --log ~/Desktop/pip3.log`, which should create a `pip3.log` file on your desktop with more verbose debugging information. Please upload this file (by just dragging it into the comment field).

Also `olefile` might not be necessary to run starcheat on OS X at all. Maybe it's enough to run:
`PATH="/usr/local/bin:$PATH" brew install starcheat --devel -vd`
and choose ignore if you see the `PermissionError: [Errno 1] Operation not permitted: '/usr/local/lib/python3.6/site-packages/OleFileIO_PL.py'` error again.

**Comment by numidark** [comment]
[pip3.log.txt](https://github.com/wizzomafizzo/starcheat/files/1228196/pip3.log.txt)

**Comment by numidark** [comment]
"PATH="/usr/local/bin:$PATH" brew install starcheat --devel -vd" Works :D

**Comment by numidark** [comment]
If necessary for you : 

> 
PATH="/usr/local/bin:$PATH" brew install starcheat --devel -vd
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (caskroom/cask, homebrew/core).
==> Updated Formulae
ace             aws-sdk-cpp     osmium-tool     sdcv            thefuck

/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/chrmoritz/homebrew-starcheat/starcheat.rb
==> Installing starcheat from chrmoritz/starcheat
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pyqt.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/qt.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sip.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/jpeg.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python3.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sqlite.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gdbm.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/makedepend.rb
/usr/bin/sandbox-exec -f /tmp/homebrew20170816-33240-1s45hke.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/chrmoritz/homebrew-starcheat/starcheat.rb --verbose --debug --devel
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/chrmoritz/homebrew-starcheat/starcheat.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pyqt.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/qt.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sip.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/jpeg.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/git.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python3.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
==> Cloning https://github.com/medeor413/starcheat.git
Updating /Users/gregory/Library/Caches/Homebrew/starcheat--git
git config remote.origin.url https://github.com/medeor413/starcheat.git
git config remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
git fetch origin
==> Checking out branch master
git checkout -f master --
Already on 'master'
Your branch is up-to-date with 'origin/master'.
git reset --hard origin/master
HEAD is now at 4994d3f Use cx_Freeze 4.3.4 instead of latest
==> pip3 install Pillow --upgrade
Requirement already up-to-date: Pillow in /usr/local/lib/python3.6/site-packages
Requirement already up-to-date: olefile in /usr/local/lib/python3.6/site-packages (from Pillow)
==> python3 build.py -v
Starting building Starcheat to build ...
Copying Starcheat python scripts
Generating python Qt templates...
Generated qt_about.py
Generated qt_appearance.py
Generated qt_blueprints.py
Generated qt_coloredit.py
Generated qt_imagebrowser.py
Generated qt_itembrowser.py
Generated qt_itemedit.py
Generated qt_itemeditoptions.py
Generated qt_listedit.py
Generated qt_mainwindow.py
Generated qt_mods.py
Generated qt_openplayer.py
Generated qt_options.py
Generated qt_quests.py
Generated qt_ship.py
Generated qt_techs.py
Generated qt_variantedit.py
Generating python Qt resource...
Generated resources_rc.py
Script build is complete!
==> Cleaning
==> Finishing up
ln -s ../Cellar/starcheat/1.0/bin/starcheat starcheat
/usr/bin/sandbox-exec -f /tmp/homebrew20170816-33620-10ef33j.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/chrmoritz/homebrew-starcheat/starcheat.rb --devel -vd --devel
/usr/local/Homebrew/Library/Homebrew/postinstall.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/chrmoritz/homebrew-starcheat/starcheat.rb
==> Caveats
You can run this to symlink the StarCheat.app into your Application folder:
  `brew linkapps starcheat`
or just run if from:
  /usr/local/opt/starcheat/StarCheat.app
==> Summary
🍺  /usr/local/Cellar/starcheat/1.0: 53 files, 2.7MB, built in 15 seconds
>

**Comment by chrmoritz** [comment]
Your `pip3.log` didn't contained an error at all too. So maybe it was really caused by something pickup up system python over homebrew python. You should really follow the last brew doctor warning to correct your $PATH permanently by running `echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bash_profile`.

**Comment by numidark** [comment]
Thank you for you're help !
Courage for the continuation of work, good continuation :)
