### ISSUE TITLE
Icon rendering issues

### ISSUE THREAD

**Issue by LoPhatKao** [wizzomafizzo/starcheat#57]
![starcheat_gfxerr](https://f.cloud.github.com/assets/6551387/2148588/68eb5f36-93e8-11e3-8bc5-49731d4a440b.png)

horizontally squished sword in hand
black border around medkit
probly some others ;)

only seen these since pillow was added

**Comment by wizzomafizzo** [comment]
- [ ] prefer live color replaced image in item instance to default

**Comment by wizzomafizzo** [comment]
not gonna bother with the background, will just make things harder to see. icons now use color replacement (except some types but that will be handled in the other ticket). icons have their whitespace trimmed and stopped from squishing. sword/gun/sapling etc images will be handled separately
